//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BankingEntities1 : DbContext
    {
        public BankingEntities1()
            : base("name=BankingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account_Holder> Account_Holder { get; set; }
        public virtual DbSet<Beneficiary> Beneficiaries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
    
        public virtual ObjectResult<display_customers_Result> display_customers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<display_customers_Result>("display_customers");
        }
    
        public virtual ObjectResult<display_customer_requests_Result> display_customer_requests()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<display_customer_requests_Result>("display_customer_requests");
        }
    
        public virtual ObjectResult<display_Acccount_Holder_Result> display_Acccount_Holder()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<display_Acccount_Holder_Result>("display_Acccount_Holder");
        }
    
        public virtual ObjectResult<display_customer_requests1_Result> display_customer_requests1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<display_customer_requests1_Result>("display_customer_requests1");
        }
    
        public virtual ObjectResult<display_Beneficiary_Result> display_Beneficiary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<display_Beneficiary_Result>("display_Beneficiary");
        }
    
        public virtual ObjectResult<display_Transactions_Result> display_Transactions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<display_Transactions_Result>("display_Transactions");
        }
    
        public virtual int block_account(string customer_id)
        {
            var customer_idParameter = customer_id != null ?
                new ObjectParameter("customer_id", customer_id) :
                new ObjectParameter("customer_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("block_account", customer_idParameter);
        }
    
        public virtual int unblock_account(string customer_id)
        {
            var customer_idParameter = customer_id != null ?
                new ObjectParameter("customer_id", customer_id) :
                new ObjectParameter("customer_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("unblock_account", customer_idParameter);
        }
    
        public virtual int credit_account(Nullable<decimal> account_no, Nullable<decimal> balance)
        {
            var account_noParameter = account_no.HasValue ?
                new ObjectParameter("account_no", account_no) :
                new ObjectParameter("account_no", typeof(decimal));
    
            var balanceParameter = balance.HasValue ?
                new ObjectParameter("balance", balance) :
                new ObjectParameter("balance", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("credit_account", account_noParameter, balanceParameter);
        }
    
        public virtual int debit_account(Nullable<decimal> account_no, Nullable<decimal> balance)
        {
            var account_noParameter = account_no.HasValue ?
                new ObjectParameter("account_no", account_no) :
                new ObjectParameter("account_no", typeof(decimal));
    
            var balanceParameter = balance.HasValue ?
                new ObjectParameter("balance", balance) :
                new ObjectParameter("balance", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("debit_account", account_noParameter, balanceParameter);
        }
    
        public virtual ObjectResult<fetch_beneficiaries_Result> fetch_beneficiaries(Nullable<decimal> account_no)
        {
            var account_noParameter = account_no.HasValue ?
                new ObjectParameter("account_no", account_no) :
                new ObjectParameter("account_no", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<fetch_beneficiaries_Result>("fetch_beneficiaries", account_noParameter);
        }
    
        public virtual ObjectResult<fetch_pending_customer_requests_Result> fetch_pending_customer_requests()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<fetch_pending_customer_requests_Result>("fetch_pending_customer_requests");
        }
    
        public virtual int approve_account(Nullable<decimal> service_ref_no)
        {
            var service_ref_noParameter = service_ref_no.HasValue ?
                new ObjectParameter("service_ref_no", service_ref_no) :
                new ObjectParameter("service_ref_no", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("approve_account", service_ref_noParameter);
        }
    
        public virtual int decline_account(Nullable<decimal> service_ref_no)
        {
            var service_ref_noParameter = service_ref_no.HasValue ?
                new ObjectParameter("service_ref_no", service_ref_no) :
                new ObjectParameter("service_ref_no", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("decline_account", service_ref_noParameter);
        }
    
        public virtual ObjectResult<fetch_user_profile_Result> fetch_user_profile(Nullable<decimal> service_ref_no)
        {
            var service_ref_noParameter = service_ref_no.HasValue ?
                new ObjectParameter("service_ref_no", service_ref_no) :
                new ObjectParameter("service_ref_no", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<fetch_user_profile_Result>("fetch_user_profile", service_ref_noParameter);
        }
    
        public virtual ObjectResult<fetch_successful_transaction_Result> fetch_successful_transaction(string ref_id)
        {
            var ref_idParameter = ref_id != null ?
                new ObjectParameter("ref_id", ref_id) :
                new ObjectParameter("ref_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<fetch_successful_transaction_Result>("fetch_successful_transaction", ref_idParameter);
        }
    
        public virtual int registerforib(string customer_id, string login_pass, Nullable<decimal> trans_pass)
        {
            var customer_idParameter = customer_id != null ?
                new ObjectParameter("customer_id", customer_id) :
                new ObjectParameter("customer_id", typeof(string));
    
            var login_passParameter = login_pass != null ?
                new ObjectParameter("login_pass", login_pass) :
                new ObjectParameter("login_pass", typeof(string));
    
            var trans_passParameter = trans_pass.HasValue ?
                new ObjectParameter("trans_pass", trans_pass) :
                new ObjectParameter("trans_pass", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("registerforib", customer_idParameter, login_passParameter, trans_passParameter);
        }
    
        public virtual ObjectResult<display_Acccount_Holder1_Result> display_Acccount_Holder1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<display_Acccount_Holder1_Result>("display_Acccount_Holder1");
        }
    
        public virtual ObjectResult<account_summary_Result> account_summary(Nullable<decimal> account_no)
        {
            var account_noParameter = account_no.HasValue ?
                new ObjectParameter("account_no", account_no) :
                new ObjectParameter("account_no", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<account_summary_Result>("account_summary", account_noParameter);
        }
    
        public virtual ObjectResult<string> send_email(Nullable<decimal> service_ref_no)
        {
            var service_ref_noParameter = service_ref_no.HasValue ?
                new ObjectParameter("service_ref_no", service_ref_no) :
                new ObjectParameter("service_ref_no", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("send_email", service_ref_noParameter);
        }
    }
}
