//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Account_Holder = new HashSet<Account_Holder>();
        }
    
        public decimal service_ref_no { get; set; }
        public string title { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string father_name { get; set; }
        public decimal mobile_no { get; set; }
        public string email_id { get; set; }
        public decimal aadhar_no { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string res_addr_line1 { get; set; }
        public string res_addr_line2 { get; set; }
        public string res_landmark { get; set; }
        public string res_state { get; set; }
        public string res_city { get; set; }
        public decimal res_pincode { get; set; }
        public string perm_addr_line1 { get; set; }
        public string perm_addr_line2 { get; set; }
        public string perm_landmark { get; set; }
        public string perm_state { get; set; }
        public string perm_city { get; set; }
        public decimal perm_pincode { get; set; }
        public string occ_type { get; set; }
        public string inc_source { get; set; }
        public decimal gross_annual_inc { get; set; }
        public string acct_type { get; set; }
        public string acct_status { get; set; }
        public string opt_debit_card { get; set; }
        public string opt_netbanking { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Holder> Account_Holder { get; set; }
    }
}
