//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string ref_id { get; set; }
        public string mode { get; set; }
        public decimal recipient_acct { get; set; }
        public decimal account_no { get; set; }
        public decimal amount { get; set; }
        public System.DateTime trans_date { get; set; }
        public string remarks { get; set; }
    
        public virtual Account_Holder Account_Holder { get; set; }
    }
}
